name: Update DataBase
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  
jobs:
  update_db:
    name: Update MongoDB of App daily
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pipenv
        run:  pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install Dependencies
        run: pipenv install
      - name: Run Script
        env:
          MONGO_URI: ${{ secrets.MONGODB_CONNECTION_URI }}
        run: |
          pipenv run test2.py
          #python DS_job_DB.py
    
